[".config/tmux/plugins/tpm"]
type = "archive"
url = "https://github.com/tmux-plugins/tpm/archive/master.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "672h"

[".config/yazi/plugins/exifaudio.yazi"]
type = "archive"
url = "https://github.com/Sonico98/exifaudio.yazi/archive/master.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "672h"

[".config/yazi/plugins/starship.yazi"]
type = "archive"
url = "https://github.com/Rolv-Apneseth/starship.yazi/archive/master.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "672h"

{{- if ne .chezmoi.os "linux" -}}
# Linux only external files
[".local/share/fonts/FiraCodeNerdFont"]
type = "archive"
url = "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/FiraCode.tar.xz"
refreshPeriod = "672h"
{{- end -}}
