gui:
  authorColors:
    "Eve Jensen": "magenta"
  nerdFontsVersion: "3"
  showNumstatInFilesView: true
  statusPanelView: "allBranchesLog"
  theme:
    selectedLineBgColor:
      - underline
os:
  editPreset: "nvim"
notARepository: "skip"
