format = """$all$os$jobs$battery$time$status$sudo$container$shell$character"""
command_timeout = 1000

# Different prompt symbol
[character]
success_symbol = '[>](bold green)'
error_symbol = '[>](bold red)'

# Battery
[[battery.display]]
threshold = 20 # default 10

# Command duration
[cmd_duration]
show_milliseconds = true

# Git
[git_metrics]
disabled = false

[os]
format = '[$symbol ]($style)'
disabled = true

# Status; essentially exit codes
[status]
format = '[$symbol$status]($style) '
disabled = false

[sudo]
format = '[$symbol]($style)'
symbol = '! '
disabled = true

[time]
disabled = true

# Symbols
[aws]
symbol = 'ó°¸ '

[azure]
symbol = 'ó° … '

[buf]
symbol = 'ï’ '

[c]
symbol = 'î˜ '

[cmake]
symbol = 'ó°”· '

[conda]
symbol = 'ó±” '

[crystal]
symbol = 'î˜¯ '

[dart]
symbol = 'î˜ '

[directory]
read_only = ' ó°Œ¾'

[docker_context]
symbol = 'ïŒˆ '

[dotnet]
symbol = 'ó°ª® '

[elixir]
symbol = 'î˜­ '

[elm]
symbol = 'î˜¬ '

[erlang]
symbol = 'î± '

[fossil_branch]
symbol = 'ï˜ '

[git_branch]
symbol = 'ï˜ '

[golang]
symbol = 'î˜§ '

[guix_shell]
symbol = 'ïŒ¥ '

[gradle]
symbol = 'î™  '

[haskell]
symbol = 'î· '

[haxe]
symbol = 'î™¦ '

[hg_branch]
symbol = 'ï˜ '

[hostname]
ssh_symbol = 'î¬ '

[java]
symbol = 'î‰– '

[julia]
symbol = 'î˜¤ '

[kotlin]
symbol = 'ó±ˆ™ '

[kubernetes]
symbol = 'ó±ƒ¾ '

[lua]
symbol = 'î˜  '

[memory_usage]
symbol = 'ó°› '

[meson]
symbol = 'ó°”· '

[nim]
symbol = 'î™· '

[nix_shell]
symbol = 'ïŒ“ '

[nodejs]
symbol = 'îœ˜ '

[os.symbols]
Alpaquita = 'îª¢ '
Alpine = 'ïŒ€ '
Amazon = 'ï‰° '
Android = 'ï…» '
Arch = 'ïŒƒ '
Artix = 'ïŒŸ '
CentOS = 'ïŒ„ '
Debian = 'ïŒ† '
DragonFly = 'îŠ '
Emscripten = 'ïˆ… '
EndeavourOS = 'ïŒ¢ '
Fedora = 'ïŒŠ '
FreeBSD = 'ïŒŒ '
Garuda = 'ó°›“ '
Gentoo = 'ïŒ '
HardenedBSD = 'ó°Œ '
Illumos = 'ïŒ¦ '
Linux = 'ïŒš '
Mabox = 'î¬© '
Macos = 'ïŒ‚ '
Manjaro = 'ïŒ’ '
Mariner = 'ï‡ '
MidnightBSD = 'ï†† '
Mint = 'ïŒ '
NetBSD = 'ï€¤ '
NixOS = 'ïŒ“ '
OpenBSD = 'ïŒ¨ '
openSUSE = 'ïŒ” '
OracleLinux = 'ó°Œ· '
Pop = 'ïŒª '
Raspbian = 'ïŒ• '
Redhat = 'ïŒ– '
RedHatEnterprise = 'ïŒ– '
Redox = 'ï”— '
Solus = 'ïŒ­ '
SUSE = 'ïŒ” '
Ubuntu = 'ïŒ› '
Unknown = 'ïˆ­ '
Windows = 'ó°¨¡ '

[package]
symbol = 'ó°— '

[perl]
symbol = 'î™¾ '

[php]
symbol = 'î˜ˆ '

[pijul_channel]
symbol = 'ó±—† '

[purescript]
symbol = 'î˜° '

[python]
symbol = 'îˆµ '

[rlang]
symbol = 'ó°Ÿ” '

[raku]
symbol = 'îŠ '

[ruby]
symbol = 'î‘ '

[rust]
symbol = 'î¨ '

[scala]
symbol = 'îœ· '

[spack]
symbol = 'ğŸ…¢ '

[swift]
symbol = 'î• '

[terraform]
symbol = 'ó±¢ '

[vlang]
symbol = 'îš¬ '

[zig]
symbol = 'îš© '
